import './globals.css'
import { Tinos } from 'next/font/google'

const tinos = Tinos({ subsets: ['latin'], weight: '400' })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={tinos.className}>{children}</body>
    </html>
  )
}
